import { describe, expect, it } from "vitest";
import Database from "better-sqlite3";
import { PGlite } from "@electric-sql/pglite";
import { breadcrumb } from "../src/index.js";
import { sqlite, postgres } from "../src/adapters/index.js";
import { planMigration, renderMigrationSql, EMPTY_SCHEMA_STATE } from "../src/db/ddl.js";

describe("planMigration", () => {
  it("plans a full fresh schema for postgres", () => {
    const plan = planMigration("postgres", EMPTY_SCHEMA_STATE);
    expect(plan.createdTables).toEqual(["breadcrumb_spans", "breadcrumb_meta"]);
    const sql = plan.statements.join("\n");
    expect(sql).toContain("CREATE TABLE IF NOT EXISTS breadcrumb_spans");
    expect(sql).toContain("BIGINT"); // integer → BIGINT on pg
    expect(sql).toContain("JSONB"); // json → JSONB on pg
    expect(sql).toContain("CREATE INDEX IF NOT EXISTS breadcrumb_spans_user_id");
    expect(sql).toContain("CREATE TABLE IF NOT EXISTS breadcrumb_meta");
  });

  it("uses SQLite types for the sqlite dialect", () => {
    const sql = planMigration("sqlite", EMPTY_SCHEMA_STATE).statements.join("\n");
    expect(sql).toContain("INTEGER"); // integer → INTEGER on sqlite
    expect(sql).not.toContain("BIGINT");
    expect(sql).not.toContain("JSONB"); // json → TEXT on sqlite
  });

  it("plans only the delta for a partially-migrated table", async () => {
    const db = new Database(":memory:");
    db.exec("CREATE TABLE breadcrumb_spans (id TEXT PRIMARY KEY, trace_id TEXT)");
    const plan = planMigration("sqlite", await sqlite(db).inspectSchema());
    const sql = plan.statements.join("\n");
    expect(sql).toContain("ALTER TABLE breadcrumb_spans ADD COLUMN reasoning_tokens");
    expect(plan.addedColumns).toContain("breadcrumb_spans.reasoning_tokens");
    expect(sql).not.toContain("ADD COLUMN id"); // already present
  });

  it("is idempotent — no statements once migrated (sqlite + postgres)", async () => {
    const lite = sqlite(new Database(":memory:"));
    await lite.migrate();
    expect(planMigration("sqlite", await lite.inspectSchema()).statements).toEqual([]);

    const db = new PGlite();
    const pg = postgres({ query: (t, v) => db.query(t, v as never[]) });
    await pg.migrate();
    expect(planMigration("postgres", await pg.inspectSchema()).statements).toEqual([]);
  });

  it("renders a reviewable .sql file", () => {
    const plan = planMigration("postgres", EMPTY_SCHEMA_STATE);
    const sql = renderMigrationSql("postgres", plan, "2026-07-24T00:00:00.000Z");
    expect(sql).toContain("-- Generated by `breadcrumb generate`");
    expect(sql).toContain("-- Dialect: postgres");
    expect(sql.trim().endsWith(";")).toBe(true);
  });
});

describe("migrations option", () => {
  it("auto (default) creates the schema on first use", async () => {
    const bc = breadcrumb({ database: sqlite(new Database(":memory:")), environment: "test" });
    await expect(bc.api.listEnvironments()).resolves.toEqual([]);
  });

  it("manual skips runtime DDL, so the table isn't created", async () => {
    const bc = breadcrumb({
      database: sqlite(new Database(":memory:")),
      environment: "test",
      migrations: "manual",
    });
    await expect(bc.api.listEnvironments()).rejects.toThrow();
  });
});
