// Bakes the built single-file SPA into core as a TS module. Core serves it
// with an injected <base href>, so it works at any mount path and in every
// bundler (no files read from node_modules at runtime).
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const html = readFileSync(join(here, "../dist/index.html"), "utf8");
const out = join(here, "../../core/src/ui/app-html.gen.ts");

writeFileSync(
  out,
  `// Generated by \`npm run build --workspace=packages/ui\` — do not edit.\nexport const APP_HTML: string = ${JSON.stringify(html)};\n`
);
console.log(`emitted ${out} (${(html.length / 1024).toFixed(0)} KB)`);
