/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedNewRouteImport } from './routes/_authed/new'
import { Route as AuthedProjectsProjectIdRouteImport } from './routes/_authed/projects/$projectId'
import { Route as AuthedProjectsProjectIdIndexRouteImport } from './routes/_authed/projects/$projectId/index'
import { Route as AuthedProjectsProjectIdTracesRouteImport } from './routes/_authed/projects/$projectId/traces'
import { Route as AuthedProjectsProjectIdSettingsRouteImport } from './routes/_authed/projects/$projectId/settings'
import { Route as AuthedProjectsProjectIdTraceTraceIdRouteImport } from './routes/_authed/projects/$projectId/trace.$traceId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNewRoute = AuthedNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProjectsProjectIdRoute = AuthedProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProjectsProjectIdIndexRoute =
  AuthedProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedProjectsProjectIdRoute,
  } as any)
const AuthedProjectsProjectIdTracesRoute =
  AuthedProjectsProjectIdTracesRouteImport.update({
    id: '/traces',
    path: '/traces',
    getParentRoute: () => AuthedProjectsProjectIdRoute,
  } as any)
const AuthedProjectsProjectIdSettingsRoute =
  AuthedProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthedProjectsProjectIdRoute,
  } as any)
const AuthedProjectsProjectIdTraceTraceIdRoute =
  AuthedProjectsProjectIdTraceTraceIdRouteImport.update({
    id: '/trace/$traceId',
    path: '/trace/$traceId',
    getParentRoute: () => AuthedProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/new': typeof AuthedNewRoute
  '/projects/$projectId': typeof AuthedProjectsProjectIdRouteWithChildren
  '/projects/$projectId/settings': typeof AuthedProjectsProjectIdSettingsRoute
  '/projects/$projectId/traces': typeof AuthedProjectsProjectIdTracesRoute
  '/projects/$projectId/': typeof AuthedProjectsProjectIdIndexRoute
  '/projects/$projectId/trace/$traceId': typeof AuthedProjectsProjectIdTraceTraceIdRoute
}
export interface FileRoutesByTo {
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/new': typeof AuthedNewRoute
  '/': typeof AuthedIndexRoute
  '/projects/$projectId/settings': typeof AuthedProjectsProjectIdSettingsRoute
  '/projects/$projectId/traces': typeof AuthedProjectsProjectIdTracesRoute
  '/projects/$projectId': typeof AuthedProjectsProjectIdIndexRoute
  '/projects/$projectId/trace/$traceId': typeof AuthedProjectsProjectIdTraceTraceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authed/new': typeof AuthedNewRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/projects/$projectId': typeof AuthedProjectsProjectIdRouteWithChildren
  '/_authed/projects/$projectId/settings': typeof AuthedProjectsProjectIdSettingsRoute
  '/_authed/projects/$projectId/traces': typeof AuthedProjectsProjectIdTracesRoute
  '/_authed/projects/$projectId/': typeof AuthedProjectsProjectIdIndexRoute
  '/_authed/projects/$projectId/trace/$traceId': typeof AuthedProjectsProjectIdTraceTraceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/login'
    | '/signup'
    | '/new'
    | '/projects/$projectId'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/traces'
    | '/projects/$projectId/'
    | '/projects/$projectId/trace/$traceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accept-invite'
    | '/login'
    | '/signup'
    | '/new'
    | '/'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/traces'
    | '/projects/$projectId'
    | '/projects/$projectId/trace/$traceId'
  id:
    | '__root__'
    | '/_authed'
    | '/accept-invite'
    | '/login'
    | '/signup'
    | '/_authed/new'
    | '/_authed/'
    | '/_authed/projects/$projectId'
    | '/_authed/projects/$projectId/settings'
    | '/_authed/projects/$projectId/traces'
    | '/_authed/projects/$projectId/'
    | '/_authed/projects/$projectId/trace/$traceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/new': {
      id: '/_authed/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AuthedNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/projects/$projectId': {
      id: '/_authed/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthedProjectsProjectIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/projects/$projectId/': {
      id: '/_authed/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AuthedProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthedProjectsProjectIdRoute
    }
    '/_authed/projects/$projectId/traces': {
      id: '/_authed/projects/$projectId/traces'
      path: '/traces'
      fullPath: '/projects/$projectId/traces'
      preLoaderRoute: typeof AuthedProjectsProjectIdTracesRouteImport
      parentRoute: typeof AuthedProjectsProjectIdRoute
    }
    '/_authed/projects/$projectId/settings': {
      id: '/_authed/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof AuthedProjectsProjectIdSettingsRouteImport
      parentRoute: typeof AuthedProjectsProjectIdRoute
    }
    '/_authed/projects/$projectId/trace/$traceId': {
      id: '/_authed/projects/$projectId/trace/$traceId'
      path: '/trace/$traceId'
      fullPath: '/projects/$projectId/trace/$traceId'
      preLoaderRoute: typeof AuthedProjectsProjectIdTraceTraceIdRouteImport
      parentRoute: typeof AuthedProjectsProjectIdRoute
    }
  }
}

interface AuthedProjectsProjectIdRouteChildren {
  AuthedProjectsProjectIdSettingsRoute: typeof AuthedProjectsProjectIdSettingsRoute
  AuthedProjectsProjectIdTracesRoute: typeof AuthedProjectsProjectIdTracesRoute
  AuthedProjectsProjectIdIndexRoute: typeof AuthedProjectsProjectIdIndexRoute
  AuthedProjectsProjectIdTraceTraceIdRoute: typeof AuthedProjectsProjectIdTraceTraceIdRoute
}

const AuthedProjectsProjectIdRouteChildren: AuthedProjectsProjectIdRouteChildren =
  {
    AuthedProjectsProjectIdSettingsRoute: AuthedProjectsProjectIdSettingsRoute,
    AuthedProjectsProjectIdTracesRoute: AuthedProjectsProjectIdTracesRoute,
    AuthedProjectsProjectIdIndexRoute: AuthedProjectsProjectIdIndexRoute,
    AuthedProjectsProjectIdTraceTraceIdRoute:
      AuthedProjectsProjectIdTraceTraceIdRoute,
  }

const AuthedProjectsProjectIdRouteWithChildren =
  AuthedProjectsProjectIdRoute._addFileChildren(
    AuthedProjectsProjectIdRouteChildren,
  )

interface AuthedRouteChildren {
  AuthedNewRoute: typeof AuthedNewRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedProjectsProjectIdRoute: typeof AuthedProjectsProjectIdRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedNewRoute: AuthedNewRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedProjectsProjectIdRoute: AuthedProjectsProjectIdRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
