import {
  META_TABLE,
  SPANS_TABLE,
  metaColumns,
  spanColumns,
  spanIndexes,
  type ColumnSpec,
} from "./schema.js";
import type { Dialect, MigrationPlan, SchemaState } from "./types.js";

// Column types map to each dialect's native types. JSON is stored as text in
// SQLite (stringified) and JSONB in Postgres.
const TYPE_MAP: Record<Dialect, Record<ColumnSpec["type"], string>> = {
  postgres: { text: "TEXT", integer: "BIGINT", real: "DOUBLE PRECISION", json: "JSONB" },
  sqlite: { text: "TEXT", integer: "INTEGER", real: "REAL", json: "TEXT" },
};

function columnDdl(dialect: Dialect, name: string, spec: ColumnSpec): string {
  const parts = [name, TYPE_MAP[dialect][spec.type]];
  if (spec.primary) parts.push("PRIMARY KEY");
  if (!spec.nullable && !spec.primary) parts.push("NOT NULL");
  return parts.join(" ");
}

function createTableSql(dialect: Dialect, table: string, columns: Record<string, ColumnSpec>): string {
  const cols = Object.entries(columns)
    .map(([name, spec]) => columnDdl(dialect, name, spec))
    .join(", ");
  return `CREATE TABLE IF NOT EXISTS ${table} (${cols})`;
}

function addColumnSql(dialect: Dialect, table: string, name: string, spec: ColumnSpec): string {
  // Additive columns are nullable so existing rows stay valid. Postgres supports
  // IF NOT EXISTS on ADD COLUMN; SQLite doesn't, but the plan only adds missing ones.
  const guard = dialect === "postgres" ? "IF NOT EXISTS " : "";
  return `ALTER TABLE ${table} ADD COLUMN ${guard}${name} ${TYPE_MAP[dialect][spec.type]}`;
}

function createIndexSql(table: string, idx: { name: string; columns: string[] }): string {
  return `CREATE INDEX IF NOT EXISTS ${idx.name} ON ${table} (${idx.columns.join(", ")})`;
}

/**
 * Diff the current schema against a live database's state and return the DDL to
 * reconcile it. The single source of truth for both `migrate()` (which executes
 * the statements) and `generate` (which writes them to a file).
 */
export function planMigration(dialect: Dialect, state: SchemaState): MigrationPlan {
  const statements: string[] = [];
  const createdTables: string[] = [];
  const addedColumns: string[] = [];

  if (!state.spansExists) {
    statements.push(createTableSql(dialect, SPANS_TABLE, spanColumns));
    createdTables.push(SPANS_TABLE);
  } else {
    for (const [name, spec] of Object.entries(spanColumns)) {
      if (state.spansColumns.has(name)) continue;
      statements.push(addColumnSql(dialect, SPANS_TABLE, name, spec));
      addedColumns.push(`${SPANS_TABLE}.${name}`);
    }
  }

  for (const idx of spanIndexes) {
    if (!state.indexNames.has(idx.name)) statements.push(createIndexSql(SPANS_TABLE, idx));
  }

  if (!state.metaExists) {
    statements.push(createTableSql(dialect, META_TABLE, metaColumns));
    createdTables.push(META_TABLE);
  }

  return { statements, createdTables, addedColumns };
}

/** The empty state — plans a full, fresh schema without a database connection. */
export const EMPTY_SCHEMA_STATE: SchemaState = {
  spansExists: false,
  spansColumns: new Set(),
  indexNames: new Set(),
  metaExists: false,
};

/** Render a plan as a reviewable `.sql` migration file. */
export function renderMigrationSql(dialect: Dialect, plan: MigrationPlan, generatedAt: string): string {
  const header = [
    `-- Generated by \`breadcrumb generate\` at ${generatedAt}`,
    `-- Dialect: ${dialect}`,
    "-- Additive-only. Review, commit, and apply with your migration tooling.",
    "",
  ].join("\n");
  return header + plan.statements.map((s) => `${s};`).join("\n\n") + "\n";
}
